# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0c80f7c197b60fee53ae0546a82902097cc021c476aaa5415594a69273e84997e5f4363fbddf8c1bffb1ab6cdec2083386c965654e08b52fa52e779ae7615dd

test:
  secret_key_base: d343c216c2bdd065cc45685c23d8ac916f4d248733baa6a65a78d3aa24ca32acfcdd4c4fb67fb8514b335292a0424e8166e46d7aac77932e26622fd47e63c477

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
